### ISSUE TITLE
Error with Arturia MiniLab mkII

### ISSUE THREAD

**Issue by hfiguiere** [soyersoyer/sysex-controls#3]
It fails to do anything with Arturia MiniLab mkII. When I click on it:

![image](https://github.com/user-attachments/assets/4e4e0b69-57bc-4ac1-9ed5-b2c5951839af)

Console says
```
poll timeout 0

** (sysex-controls:2): WARNING **: 10:17:14.213: control value read failed

```

Clicking a second time I get:

![image](https://github.com/user-attachments/assets/29aca91f-d9a2-4b66-a224-d991e5a689bb)

```
snd_seq_connect_from(16:0) failed -16

** (sysex-controls:2): WARNING **: 10:19:06.177: Failed to connect 16:0
```

**Comment by soyersoyer** [comment]
Thanks for testing this. Could you check if it works if you reconnect the MiniLab's USB?

**Comment by hfiguiere** [comment]
That doesn't change a thing. 

Note that above, the "second time" is without quitting the app. If I quit the app it's back to square 1.

**Comment by soyersoyer** [comment]
Then it doesn't work quite like KeyStep 37. It is possible that it sends only one message after reading, not two.
Could you start an `aseqdump -p Arturia` and then try to open the controller?
Disabling ack reading from the sc-midi.c process_control_event function might help.

**Comment by soyersoyer** [comment]
I made a few changes, in theory it should work with MkII as well.

**Comment by rdbende** [comment]
Indeed. I had this problem a couple of week ago, but with the current main branch, it works well.

**Comment by soyersoyer** [comment]
> Indeed. I had this problem a couple of week ago, but with the current main branch, it works well.

Thanks for testing. Do the presets work well too?

**Comment by soyersoyer** [comment]
Presets and the controller work fine in v0.2.13.
