### ISSUE TITLE
can't save to preset 2  (MiniLab mkII)

### ISSUE THREAD

**Issue by Jafo090** [soyersoyer/sysex-controls#7]
Love this project.

I recently got a used Arturia Minilab mk II. I know its first memory/preset is read-only to service Arturia's synth app.  I borrowed a WIN10 laptop to use the MCC program:  updated the firmware, and saved a test configuration to preset 2.  I also tried to get MCC running under WINE, but gave up.  

Then I found this project;  works well, but when I try to store/save the UI "greys out" the first two presets.  I can read all presets, and write to presets 3 through 8.  So it's a minor issue:  I'm learning MIDI controllers and don't need all 7 or 8 preset spots.

**Comment by soyersoyer** [comment]
Thank you for reporting. Fixed in v0.2.13.
